<AboutDialog>:
	BoxLayout:
		size: root.size
		pos: root.pos
		orientation: "vertical"

		GridLayout:
			size_hint_y: None
			height: dp(60)
			cols: 6
			padding: dp(16)
			spacing: dp(12)

			HyperlinkLabel:
				url: "https://github.com/nicoboss/nsz"
				url_text: "GitHub"
			HyperlinkLabel:
				url: "https://pypi.org/project/nsz/"
				url_text: "Pip"
			HyperlinkLabel:
				url: "https://gbatemp.net/threads/nsz-homebrew-compatible-nsp-xci-compressor-decompressor.550556/"
				url_text: "GBAtemp"
			HyperlinkLabel:
				url: "https://github.com/nicoboss/nsz/releases"
				url_text: "Releases"
			HyperlinkLabel:
				url: "https://github.com/nicoboss/nsz/issues"
				url_text: "Issues"
			HyperlinkLabel:
				url: "https://gitlab.nicobosshard.ch/nicoboss/nsz"
				url_text: "Mirror"

		ScrollView:
			id: license_text_scrlv
			size_hint: (1, .83)

			TextInput:
				id: license_text
				background_color: (0,0,0,1)
				foreground_color: (1,1,1,1)
				height: max(self.minimum_height, license_text_scrlv.height)
				size_hint: 1, None
				readonly: True
				text: 'Failed to load license text!'

		BoxLayout:
			size_hint_y: None
			height: dp(40)

			Button:
				font_size: dp(18)
				text: "Cancel"
				on_release: root.closeAboutDialog()
