<OpenFileDialog>:
	BoxLayout:
		size: root.size
		pos: root.pos
		orientation: "vertical"
		drives_list: drives_list
		
		BoxLayout:
			size_hint_y: None
			height: 30
			id: drives_list
		
		FileChooserListView:
			id: filechooser

		BoxLayout:
			size_hint_y: None
			height: 30
			Button:
				text: "Cancel"
				on_release: root.cancel()

			Button:
				text: "Load"
				on_release: root.load(filechooser.path, filechooser.selection)
